// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL_5WdOSbhD_A8EZyXpPVcsq7cQOwOVKY',
    appId: '1:38093386342:web:377ce5b1a59ffb939373a7',
    messagingSenderId: '38093386342',
    projectId: 'mylion-notes',
    authDomain: 'mylion-notes.firebaseapp.com',
    storageBucket: 'mylion-notes.appspot.com',
    measurementId: 'G-M5Z3XWFZMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyp1pwFs9AGxJoMeaFlb5srMj9eyWmsRU',
    appId: '1:38093386342:android:c58bae8fb15416819373a7',
    messagingSenderId: '38093386342',
    projectId: 'mylion-notes',
    storageBucket: 'mylion-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCru7qzI-j5Vge3O3guVo_7ku2tiw4LK3Y',
    appId: '1:38093386342:ios:2c28a7d11bf9f9179373a7',
    messagingSenderId: '38093386342',
    projectId: 'mylion-notes',
    storageBucket: 'mylion-notes.appspot.com',
    iosBundleId: 'es.aslansn.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCru7qzI-j5Vge3O3guVo_7ku2tiw4LK3Y',
    appId: '1:38093386342:ios:2574990b85119eeb9373a7',
    messagingSenderId: '38093386342',
    projectId: 'mylion-notes',
    storageBucket: 'mylion-notes.appspot.com',
    iosBundleId: 'es.aslansn.mynotes.RunnerTests',
  );
}
